"""Migrate model task

Revision ID: 92326b397c0f
Revises: c7095449a0b7
Create Date: 2020-08-06 13:07:34.456284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92326b397c0f'
down_revision = 'c7095449a0b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    # ### end Alembic commands ###
